version: '3.9'

services:
  vue-app:
    container_name: vue-app
    build:
      context: './'
      dockerfile: Dockerfile.dev
    volumes:
      - './:/app/'
      - '/app/node_modules'
    ports:
      - '8080:8080'
    restart: always